// <auto-generated />
namespace CitySpeaks_samle.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _230320171 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_230320171));
        
        string IMigrationMetadata.Id
        {
            get { return "201703230617248_23032017-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
