// <auto-generated />
namespace CitySpeaks_samle.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _020420171 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_020420171));
        
        string IMigrationMetadata.Id
        {
            get { return "201704021741050_02042017-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
